import { Directive, ElementRef, Injector, OnInit } from '@angular/core';
import { ActionPolicyBaseDirective } from './action-policy-base.directive';
/**
 * Directive that hides somes actions if the provided rules are evaluated to `true`.
 * It is mainly used in the `actions` button components configured the screens generated by `UI Studio` tool.
 *
 * You can override the ActionPolicy directive, if needed, all the generated methods & variables of the Base component in this class.
 * @AutoSkip Do not remove this tag to keep your file out of regeneration.
 * @Note This component is generated once and will no more be erased by the generator.
 */
@Directive({
  selector: '[plmActionPolicy]',
  standalone: true,
})
export class ActionPolicyDirective extends ActionPolicyBaseDirective implements OnInit {
  constructor(elementRef: ElementRef, injector: Injector) {
    super(elementRef, injector);
  }
}
