import { Component } from '@angular/core';
import {
  COMPONENT_IMPORTS,
  COMPONENT_PROVIDERS,
  ValidatorComponentBase,
} from './validator.component-base';
/**
 * Validator that validates a `FormControl` and diplays errors in case of failure.
 * It is mainly used in the `edit` and `searchInput` screens generated by UI Studio tool.
 *
 * This class should not be modified.
 * @AutoSkip Do not remove this tag to keep your file out of regeneration.
 * @Note This component is generated once and will no more be erased by the generator.
 */
@Component({
  selector: 'app-validator',
  templateUrl: './validator.component.html',
  standalone: true,
  imports: [...COMPONENT_IMPORTS],
  providers: [...COMPONENT_PROVIDERS],
})
export class ValidatorComponent extends ValidatorComponentBase {}
