/**
 * This is an example of a selector based on a CSS class name generated by Veggo UI Platform
 * for writing selectors not coupled to CSS Class Names or HTML Attributes that may change
 */
export const getMyButton = () => cy.get('.e2e-button')
