import { DatePipe } from '@angular/common';
import { Pipe, PipeTransform } from '@angular/core';

import { ProfileService } from '@services/profile/profile.service';
import { NumberPipe } from '@shared/pipes/number.pipe';
import { GridBasePipe } from './grid-base.pipe';
/**
 * Pipe that formats the Column values. It is mainly used in the `Search` & `Edit Collection` & `Tree` screens generated by `UI Studio` tool.
 *You can override, if needed, all the generated methods & variables of the Base Pipe in this class.
 *
 * @AutoSkip Do not remove this tag to keep your file out of regeneration.
 * @Note This pipe is generated once and will no more be erased by the generator.
 */
@Pipe({
  name: 'gridPipe',
  standalone: true,
})
export class GridPipe extends GridBasePipe implements PipeTransform {
  constructor(profile: ProfileService, numberPipe: NumberPipe, datePipe: DatePipe) {
    super(profile, numberPipe, datePipe);
  }
  /**
   * Formats the provided column's value
   * @param value
   * @param colType
   * @param temporalType
   * @param datePrecision
   */
  transform(value: any, colType: string, temporalType?: string, datePrecision?: string): string {
    return super.transform(value, colType, temporalType, datePrecision);
  }
}
